Repository FromDoppler/doppler-billing-user, pull requests merged in 2024-10, with the labels that each got.

#601 [no-task] - Fix issue when send information to sap
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/Utils/BillingHelper.cs
Labels: size/M

#602 [DAT-2210] - Send IsCustom plan to sap
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/ExternalServices/Sap/SapAdditionalServiceDto.cs
  Doppler.BillingUser/Model/AdditionalService.cs
Labels: size/XS

#603 [no-task] Fix bug in conversation buy logic
  Doppler.BillingUser/Controllers/BillingController.cs
Labels: size/XS

#604 [DAT-2203] - Support buy conversations plan to CM user from Admin
  Doppler.BillingUser.Test/BillingControllerTest.cs
  Doppler.BillingUser.Test/PostAgreementTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/Enums/AccountTypeEnum.cs
  Doppler.BillingUser/Enums/UserTypeEnum.cs
  Doppler.BillingUser/Infrastructure/ClientManagerRepository.cs
  Doppler.BillingUser/Infrastructure/IClientManagerRepository.cs
  Doppler.BillingUser/Infrastructure/UserRepository.cs
  Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForCreditCardMapper.cs
  Doppler.BillingUser/Mappers/AccountingEntry/AccountingEntryForMercadopagoMapper.cs
  Doppler.BillingUser/Mappers/AccountingEntry/IAccountingEntryMapper.cs
  Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForCreditCardMapper.cs
  Doppler.BillingUser/Model/User.cs
  Doppler.BillingUser/Startup.cs
Labels: size/XL

#605 [No-Ticket] fix issue when the conversation plan is updated
  Doppler.BillingUser/Controllers/BillingController.cs
Labels: size/XS

#607 [DAT-2242] - Add email property in addionalservice object
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/ExternalServices/Sap/SapAdditionalServiceDto.cs
  Doppler.BillingUser/Utils/BillingHelper.cs
Labels: size/S
