Repository FromDoppler/doppler-billing-user, pull requests merged in 2024-03, with the labels that each got.

#527 [DAT-1905] Change auth policy for get invoices endpoint and reprocess endp…
  Doppler.BillingUser/Controllers/BillingController.cs
Labels: size/XS

#532 [DAT-1897] - fix issue with timeout when call account plan api
  Doppler.BillingUser.Test/AccountPlansServiceTest.cs
  Doppler.BillingUser/ExternalServices/AccountPlansApi/AccountPlansService.cs
Labels: size/S

#535 [DAT-1897] - fix use with timeout when try to get the amount details
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/Services/EmailTemplatesService.cs
Labels: size/M

#536 fix: timeout issue
  Doppler.BillingUser/Controllers/BillingController.cs
Labels: size/M

#538 [DAT-1933] Add TimeCollector
  Doppler.BillingUser.Test/AccountPlansServiceTest.cs
  Doppler.BillingUser.Test/ExternalServices/CloverServiceTest.cs
  Doppler.BillingUser.Test/Infrastructure/CurrencyRepositoryTest.cs
  Doppler.BillingUser.Test/MercadoPagoServiceTest.cs
  Doppler.BillingUser.Test/RelayEmailSenderTest.cs
  Doppler.BillingUser.Test/SapServiceTest.cs
  Doppler.BillingUser.Test/ZohoServiceTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/ExternalServices/AccountPlansApi/AccountPlansService.cs
  Doppler.BillingUser/ExternalServices/Aws/AwsS3Service.cs
  Doppler.BillingUser/ExternalServices/Clover/CloverService.cs
  Doppler.BillingUser/ExternalServices/EmailSender/RelayEmailSender.cs
  Doppler.BillingUser/ExternalServices/FirstData/PaymentGateway.cs
  Doppler.BillingUser/ExternalServices/MercadoPagoApi/MercadoPagoService.cs
  Doppler.BillingUser/ExternalServices/Sap/SapService.cs
  Doppler.BillingUser/ExternalServices/Slack/SlackService.cs
  Doppler.BillingUser/ExternalServices/StaticDataCllient/StaticDataClient.cs
  Doppler.BillingUser/ExternalServices/Zoho/ZohoService.cs
  Doppler.BillingUser/Infrastructure/BillingRepository.cs
  Doppler.BillingUser/Infrastructure/CurrencyRepository.cs
  Doppler.BillingUser/Infrastructure/PromotionRepository.cs
  Doppler.BillingUser/Infrastructure/UserPaymentHistoryRepository.cs
  Doppler.BillingUser/Infrastructure/UserRepository.cs
  Doppler.BillingUser/Services/EmailTemplatesService.cs
  Doppler.BillingUser/Startup.cs
  Doppler.BillingUser/TimeCollector/ITimeCollector.cs
  Doppler.BillingUser/TimeCollector/TimeCollector.cs
  Doppler.BillingUser/TimeCollector/TimeCollectorItem.cs
  Doppler.BillingUser/TimeCollector/TimeCollectorLogWritter.cs
  Doppler.BillingUser/TimeCollector/TimeCollectorLogWritterSettings.cs
  Doppler.BillingUser/TimeCollector/TimeCollectorScope.cs
  Doppler.BillingUser/TimeCollector/TimeCollectorServiceCollectionExtensions.cs
Labels: size/XL

#539 [DAT-1928] - Crear endpoint para la contratación de packs de landing (Primera Compra)
  Doppler.BillingUser.Test/BuyLandingPlanTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
  Doppler.BillingUser/Enums/PlanTypeEnum.cs
  Doppler.BillingUser/Enums/SourceTypeEnum.cs
  Doppler.BillingUser/Infrastructure/BillingRepository.cs
  Doppler.BillingUser/Infrastructure/IBillingRepository.cs
  Doppler.BillingUser/Infrastructure/ILandingPlanUserRepository.cs
  Doppler.BillingUser/Infrastructure/LandingPlanUserRepository.cs
  Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/BillingCreditForAutomaticDebitMapper.cs
  Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/BillingCreditForCreditCardMapper.cs
  Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/BillingCreditForMercadopagoMapper.cs
  Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/BillingCreditForTransferMapper.cs
  Doppler.BillingUser/Mappers/BillingCredit/LandingPlan/IBillingCreditMapper.cs
  Doppler.BillingUser/Model/BillingCreditModel.cs
  Doppler.BillingUser/Model/BuyLandingPlans.cs
  Doppler.BillingUser/Model/LandingPlan.cs
  Doppler.BillingUser/Model/LandingPlanUser.cs
  Doppler.BillingUser/Startup.cs
Labels: size/XXL

#540 [DAT-1950] - Update prod config to use clover api
  Doppler.BillingUser/appsettings.json
Labels: size/XS
