Repository FromDoppler/doppler-billing-user, pull requests merged in 2025-04, with the labels that each got.

#661 Dat 2451
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/Infrastructure/BillingRepository.cs
  Doppler.BillingUser/Infrastructure/IBillingRepository.cs
  Doppler.BillingUser/Infrastructure/IUserRepository.cs
  Doppler.BillingUser/Infrastructure/UserRepository.cs
Labels: size/M

#662 Dat 2433
  Doppler.BillingUser.Test/AddOnCancellationTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
Labels: size/L

#663 [DAT-2426] - Update endpoint to supports buy push notification plan
  Doppler.BillingUser.Test/ActivateAddOnTest.cs
  Doppler.BillingUser.Test/BuyAddOnPlanTest.cs
  Doppler.BillingUser.Test/GetCurrentPlanTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/Enums/BillingCreditTypeEnum.cs
  Doppler.BillingUser/Enums/PlanTypeEnum.cs
  Doppler.BillingUser/Enums/SourceTypeEnum.cs
  Doppler.BillingUser/Infrastructure/IPushNotificationPlanUserRepository.cs
  Doppler.BillingUser/Infrastructure/PushNotificationPlanUserRepository.cs
  Doppler.BillingUser/Infrastructure/UserRepository.cs
  Doppler.BillingUser/Mappers/AddOn/IAddOnMapper.cs
  Doppler.BillingUser/Mappers/AddOn/OnSite/OnSiteMapper.cs
  Doppler.BillingUser/Mappers/AddOn/PushNotification/PushNotificationMapper.cs
  Doppler.BillingUser/Model/BuyAddOnPlan.cs
  Doppler.BillingUser/Model/CurrentPlan.cs
  Doppler.BillingUser/Startup.cs
  Doppler.BillingUser/Utils/BillingHelper.cs
Labels: size/XXL

#664 [DAT-2432] - Include push notification plan
  Doppler.BillingUser/Controllers/BillingController.cs
Labels: size/XS

#667 [DAT-2465]
  Doppler.BillingUser.Test/AddOnCancellationTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
Labels: size/M

#670 feat: fix issue when set data from billinguserdata
  Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForAutomaticDebitMapper.cs
  Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForMercadopagoMapper.cs
  Doppler.BillingUser/Mappers/BillingCredit/AddOns/BillingCreditForTransferMapper.cs
Labels: size/M

#669 DAT-2442
  Doppler.BillingUser.Test/ActivateAddOnTest.cs
  Doppler.BillingUser.Test/BuyAddOnPlanTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/ExternalServices/EmailSender/EmailNotificationsConfiguration.cs
  Doppler.BillingUser/Infrastructure/OnSitePlanRepository.cs
  Doppler.BillingUser/Infrastructure/OnSitePlanUserRepository.cs
  Doppler.BillingUser/Infrastructure/PushNotificationPlanRepository.cs
  Doppler.BillingUser/Mappers/AddOn/OnSite/OnSiteMapper.cs
  Doppler.BillingUser/Mappers/AddOn/PushNotification/PushNotificationMapper.cs
  Doppler.BillingUser/Model/OnSitePlan.cs
  Doppler.BillingUser/Model/PushNotificationPlan.cs
  Doppler.BillingUser/Services/EmailTemplatesService.cs
  Doppler.BillingUser/Services/IEmailTemplatesService.cs
  Doppler.BillingUser/appsettings.Development.json
  Doppler.BillingUser/appsettings.int.json
  Doppler.BillingUser/appsettings.json
  Doppler.BillingUser/appsettings.qa.json
Labels: size/L

#671 [DAT-2464] - Integrate email with buy push notification plan
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/Mappers/AddOn/PushNotification/PushNotificationMapper.cs
Labels: size/M
