Repository FromDoppler/doppler-billing-user, pull requests merged in 2025-01, with the labels that each got.

#636 [no-task] Fix issue cm
  Doppler.BillingUser.Test/BuyOnSitePlanTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/ExternalServices/Clover/CloverService.cs
Labels: size/M

#639 fix: fix issue
  Doppler.BillingUser/Controllers/BillingController.cs
Labels: size/XS

#634 Dat 2287
  Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/ExternalServices/BinApi/BinService.cs
  Doppler.BillingUser/ExternalServices/BinApi/BinSettings.cs
  Doppler.BillingUser/ExternalServices/BinApi/CardNotFoundException.cs
  Doppler.BillingUser/ExternalServices/BinApi/IBinService.cs
  Doppler.BillingUser/ExternalServices/BinApi/Responses/BankIdentificationNumberResponse.cs
  Doppler.BillingUser/Startup.cs
  Doppler.BillingUser/appsettings.Development.json
  Doppler.BillingUser/appsettings.int.json
  Doppler.BillingUser/appsettings.json
  Doppler.BillingUser/appsettings.qa.json
Labels: size/L

#640 Add null check
  Doppler.BillingUser/ExternalServices/Clover/CloverService.cs
Labels: size/XS

#641 Credit card schema filter
  Doppler.BillingUser.Test/PutCurrentPaymentMethodTest.cs
  Doppler.BillingUser.Test/SanitizeCreditCardNumberTest.cs
  Doppler.BillingUser/Controllers/BillingController.cs
  Doppler.BillingUser/ExternalServices/BinApi/BinService.cs
  Doppler.BillingUser/ExternalServices/BinApi/IBinService.cs
  Doppler.BillingUser/Utils/CreditCardHelper.cs
Labels: size/M
